server.port=8083

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/plm}

# Elasticsearch
elasticsearch.uris=${ELASTICSEARCH_URIS:localhost:9200}
spring.elasticsearch.uris=http://${ELASTICSEARCH_URIS:localhost:9200}

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=search-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
