server.port=8086

# Keycloak
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8081/realms/plm/protocol/openid-connect/certs}

# PLM Core Service URL (for fetching data)
plm.core.url=${PLM_CORE_URL:http://plm-core-service:8080}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
