apiVersion: apps/v1
kind: Deployment
metadata:
  name: plm-core-service
  namespace: plm
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: plm
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-angular
  namespace: plm
spec:
  replicas: 3
